services:
  salms_app:
    build: .
    container_name: salms_app
    restart: always
    volumes:
      # - ./volumes/html:/var/www/html
      - ".:/var/www/html"
    ports:
      - "8082:80"
      - "8080:8080"
      - "9000:9000"
    environment:
      PHP_FPM_POOL_NAME: "salms_app"
      AUTORUN_ENABLED: 'true'
    depends_on:
      - mysql
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: education
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

networks:
  laravel_network:

